import type { WorkflowPreset } from "./schema"

export const presets: WorkflowPreset[] = [
  {
    id: "quick-fix",
    name: "Quick Fix",
    description: "Small bug fixes. One scout, one fixer, targeted test.",
    mode: "quick_fix", rigorLevel: "fast", defaultRisk: "low",
    template: {
      id: "quick-fix", name: "Quick Fix", description: "Small bug fix",
      mode: "quick_fix", rigorLevel: "fast", riskLevel: "low",
      roles: [
        { id: "scout", agentProfile: "Scout this issue", purpose: "Map the problem", canMutate: false, allowedTools: ["read","search","lsp"], requiredInputs: [], expectedOutputs: ["problem_map"] },
        { id: "fixer", agentProfile: "Fix this issue", purpose: "Apply the fix", canMutate: true, allowedTools: ["read","write","edit","bash"], requiredInputs: ["problem_map"], expectedOutputs: ["patch"], dependsOn: ["scout"] },
        { id: "validator", agentProfile: "Validate this fix", purpose: "Run targeted tests", canMutate: false, allowedTools: ["read","bash"], requiredInputs: ["patch"], expectedOutputs: ["validation_result"], dependsOn: ["fixer"] },
      ],
      gates: [{ id: "typecheck", kind: "typecheck", required: true, appliesAfter: ["fixer"] }, { id: "targeted_test", kind: "test", required: true, appliesAfter: ["validator"] }],
      budgets: { maxTimeMs: 300000, maxParallelLanes: 1 },
      tools: { allow: ["read","write","edit","search","lsp","bash"], deny: [], requireApproval: [] },
      outputs: [{ kind: "patch", required: true }],
    },
  },
  {
    id: "prototype",
    name: "Prototype",
    description: "Fast exploration. One builder, one critic, no tests.",
    mode: "prototype", rigorLevel: "fast", defaultRisk: "low",
    template: {
      id: "prototype", name: "Prototype", description: "Build a quick prototype",
      mode: "prototype", rigorLevel: "fast", riskLevel: "low",
      roles: [
        { id: "builder", agentProfile: "Build this feature", purpose: "Create prototype", canMutate: true, allowedTools: ["read","write","edit","bash"], requiredInputs: [], expectedOutputs: ["prototype"] },
        { id: "critic", agentProfile: "Critique this prototype", purpose: "Find issues", canMutate: false, allowedTools: ["read","search"], requiredInputs: ["prototype"], expectedOutputs: ["critique"], dependsOn: ["builder"] },
      ],
      gates: [],
      budgets: { maxTimeMs: 600000, maxParallelLanes: 1 },
      tools: { allow: ["read","write","edit","search","bash"], deny: [], requireApproval: [] },
      outputs: [{ kind: "report", required: true }],
    },
  },
  {
    id: "frontend-polish",
    name: "Frontend Polish",
    description: "UI/UX work with visual smoke test.",
    mode: "polish", rigorLevel: "balanced", defaultRisk: "low",
    template: {
      id: "frontend-polish", name: "Frontend Polish", description: "Polish the UI",
      mode: "polish", rigorLevel: "balanced", riskLevel: "low",
      roles: [
        { id: "mapper", agentProfile: "Map the UI surface", purpose: "Find what to change", canMutate: false, allowedTools: ["read","search","lsp"], requiredInputs: [], expectedOutputs: ["ui_map"] },
        { id: "implementer", agentProfile: "Implement UI changes", purpose: "Apply changes", canMutate: true, allowedTools: ["read","write","edit","bash"], requiredInputs: ["ui_map"], expectedOutputs: ["patch"], dependsOn: ["mapper"] },
        { id: "smoker", agentProfile: "Visual smoke test", purpose: "Verify visually", canMutate: false, allowedTools: ["read","browser"], requiredInputs: ["patch"], expectedOutputs: ["smoke_report"], dependsOn: ["implementer"] },
      ],
      gates: [{ id: "typecheck", kind: "typecheck", required: true, appliesAfter: ["implementer"] }],
      budgets: { maxTimeMs: 600000, maxParallelLanes: 2 },
      tools: { allow: ["read","write","edit","search","lsp","bash","browser"], deny: [], requireApproval: [] },
      outputs: [{ kind: "patch", required: true }, { kind: "report", required: false }],
    },
  },
  {
    id: "backend-hardening",
    name: "Backend Hardening",
    description: "Architecture-level changes with service boundary checks.",
    mode: "refactor", rigorLevel: "rigorous", defaultRisk: "medium",
    template: {
      id: "backend-hardening", name: "Backend Hardening", description: "Harden the backend",
      mode: "refactor", rigorLevel: "rigorous", riskLevel: "medium",
      roles: [
        { id: "scout", agentProfile: "Architecture scout", purpose: "Map the subsystem", canMutate: false, allowedTools: ["read","search","lsp"], requiredInputs: [], expectedOutputs: ["arch_map"] },
        { id: "lane_a", agentProfile: "Implementation lane A", purpose: "Apply changes", canMutate: true, allowedTools: ["read","write","edit","bash"], requiredInputs: ["arch_map"], expectedOutputs: ["patch_a"], dependsOn: ["scout"] },
        { id: "lane_b", agentProfile: "Test lane", purpose: "Write and run tests", canMutate: true, allowedTools: ["read","write","bash"], requiredInputs: ["arch_map"], expectedOutputs: ["tests","test_results"], dependsOn: ["scout"] },
        { id: "auditor", agentProfile: "Audit the change", purpose: "Verify boundaries", canMutate: false, allowedTools: ["read","search","lsp","bash"], requiredInputs: ["patch_a","tests"], expectedOutputs: ["audit_report"], dependsOn: ["lane_a","lane_b"] },
      ],
      gates: [{ id: "typecheck", kind: "typecheck", required: true, appliesAfter: ["lane_a"] }, { id: "tests", kind: "test", required: true, appliesAfter: ["lane_b"] }, { id: "migration_check", kind: "lint", required: true, appliesAfter: ["lane_a"] }],
      budgets: { maxTimeMs: 1800000, maxParallelLanes: 2 },
      tools: { allow: ["read","write","edit","search","lsp","bash"], deny: [], requireApproval: [] },
      outputs: [{ kind: "patch", required: true }, { kind: "report", required: true }, { kind: "release_notes", required: true }],
      dynamicRules: [{ condition: "migration_touched", addGates: [{ id: "migration_idempotency", kind: "test", required: true, appliesAfter: ["lane_a"] }] }],
    },
  },
  {
    id: "research",
    name: "Research / Spike",
    description: "Exploration with no production code changes.",
    mode: "research", rigorLevel: "fast", defaultRisk: "low",
    template: {
      id: "research", name: "Research", description: "Explore a topic",
      mode: "research", rigorLevel: "fast", riskLevel: "low",
      roles: [
        { id: "researcher", agentProfile: "Research this topic", purpose: "Gather findings", canMutate: false, allowedTools: ["read","search","websearch"], requiredInputs: [], expectedOutputs: ["findings"] },
        { id: "prototyper", agentProfile: "Build a spike", purpose: "Quick prototype", canMutate: true, allowedTools: ["read","write","edit"], requiredInputs: ["findings"], expectedOutputs: ["spike"], dependsOn: ["researcher"] },
        { id: "critic", agentProfile: "Critique findings", purpose: "Find gaps", canMutate: false, allowedTools: ["read","search"], requiredInputs: ["findings","spike"], expectedOutputs: ["critique"], dependsOn: ["researcher","prototyper"] },
      ],
      gates: [],
      budgets: { maxTimeMs: 1200000, maxParallelLanes: 2 },
      tools: { allow: ["read","write","edit","search","websearch"], deny: [], requireApproval: [] },
      outputs: [{ kind: "report", required: true }],
    },
  },
  {
    id: "security-review",
    name: "Security Review",
    description: "Adversarial security audit with red team.",
    mode: "security_review", rigorLevel: "rigorous", defaultRisk: "high",
    template: {
      id: "security-review", name: "Security Review", description: "Audit security",
      mode: "security_review", rigorLevel: "rigorous", riskLevel: "high",
      roles: [
        { id: "mapper", agentProfile: "Map attack surface", purpose: "Find entry points", canMutate: false, allowedTools: ["read","search","lsp"], requiredInputs: [], expectedOutputs: ["attack_surface"] },
        { id: "red_team", agentProfile: "Adversarial probe", purpose: "Find vulnerabilities", canMutate: false, allowedTools: ["read","search","lsp"], requiredInputs: ["attack_surface"], expectedOutputs: ["vulnerabilities"], dependsOn: ["mapper"] },
        { id: "fixer", agentProfile: "Fix findings", purpose: "Patch vulnerabilities", canMutate: true, allowedTools: ["read","write","edit"], requiredInputs: ["vulnerabilities"], expectedOutputs: ["patch"], dependsOn: ["red_team"] },
        { id: "auditor", agentProfile: "Verify fixes", purpose: "Confirm remediation", canMutate: false, allowedTools: ["read","search","lsp","bash"], requiredInputs: ["patch"], expectedOutputs: ["verification"], dependsOn: ["fixer"] },
      ],
      gates: [{ id: "typecheck", kind: "typecheck", required: true, appliesAfter: ["fixer"] }, { id: "secret_scan", kind: "secret_scan", required: true, appliesAfter: ["fixer"] }, { id: "binder", kind: "binder", required: true, appliesAfter: ["auditor"] }],
      budgets: { maxTimeMs: 3600000, maxParallelLanes: 2 },
      tools: { allow: ["read","write","edit","search","lsp","bash"], deny: [], requireApproval: ["write","edit"] },
      outputs: [{ kind: "binder", required: true }, { kind: "patch", required: true }],
    },
  },
  {
    id: "enterprise-closure",
    name: "Enterprise Closure",
    description: "Full governed release pipeline with binder, red team, and migration auditor.",
    mode: "enterprise", rigorLevel: "enterprise", defaultRisk: "medium",
    template: {
      id: "enterprise-closure", name: "Enterprise Closure", description: "Full release pipeline",
      mode: "enterprise", rigorLevel: "enterprise", riskLevel: "medium",
      roles: [
        { id: "cartographer", agentProfile: "Map the full surface", purpose: "Inventory everything", canMutate: false, allowedTools: ["read","search","lsp","bash"], requiredInputs: [], expectedOutputs: ["surface_map"] },
        { id: "lane_a", agentProfile: "Implementation lane A", purpose: "Apply changes", canMutate: true, allowedTools: ["read","write","edit","bash"], requiredInputs: ["surface_map"], expectedOutputs: ["patch_a"], dependsOn: ["cartographer"] },
        { id: "lane_b", agentProfile: "Test lane", purpose: "Write tests", canMutate: true, allowedTools: ["read","write","bash"], requiredInputs: ["surface_map"], expectedOutputs: ["tests"], dependsOn: ["cartographer"] },
        { id: "red_team", agentProfile: "Adversarial review", purpose: "Find issues", canMutate: false, allowedTools: ["read","search","lsp"], requiredInputs: ["patch_a"], expectedOutputs: ["findings"], dependsOn: ["lane_a"] },
        { id: "auditor", agentProfile: "Release auditor", purpose: "Verify everything", canMutate: false, allowedTools: ["read","search","lsp","bash"], requiredInputs: ["patch_a","tests","findings"], expectedOutputs: ["binder"], dependsOn: ["lane_a","lane_b","red_team"] },
      ],
      gates: [
        { id: "typecheck", kind: "typecheck", required: true, appliesAfter: ["lane_a"] },
        { id: "tests", kind: "test", required: true, appliesAfter: ["lane_b"] },
        { id: "secret_scan", kind: "secret_scan", required: true, appliesAfter: ["lane_a"] },
        { id: "review", kind: "review", required: true, appliesAfter: ["red_team"] },
        { id: "binder", kind: "binder", required: true, appliesAfter: ["auditor"] },
      ],
      budgets: { maxTimeMs: 7200000, maxParallelLanes: 3 },
      tools: { allow: ["read","write","edit","search","lsp","bash"], deny: [], requireApproval: ["write"] },
      outputs: [{ kind: "binder", required: true }, { kind: "patch", required: true }, { kind: "release_notes", required: true }],
      dynamicRules: [
        { condition: "migration_touched", addGates: [{ id: "migration_idempotency", kind: "test", required: true, appliesAfter: ["lane_a"] }] },
        { condition: "ipc_touched", addGates: [{ id: "ipc_contract", kind: "test", required: true, appliesAfter: ["lane_a"] }] },
        { condition: "electron_config_touched", addGates: [{ id: "pglite_externalization", kind: "lint", required: true, appliesAfter: ["lane_a"] }] },
      ],
    },
  },
  {
    id: "refactor",
    name: "Refactor",
    description: "Restructure code with safety nets.",
    mode: "refactor", rigorLevel: "balanced", defaultRisk: "medium",
    template: {
      id: "refactor", name: "Refactor", description: "Restructure code",
      mode: "refactor", rigorLevel: "balanced", riskLevel: "medium",
      roles: [
        { id: "scout", agentProfile: "Scout the refactor surface", purpose: "Map what to change", canMutate: false, allowedTools: ["read","search","lsp"], requiredInputs: [], expectedOutputs: ["refactor_map"] },
        { id: "refactorer", agentProfile: "Apply the refactor", purpose: "Restructure", canMutate: true, allowedTools: ["read","write","edit","bash"], requiredInputs: ["refactor_map"], expectedOutputs: ["patch"], dependsOn: ["scout"] },
        { id: "tester", agentProfile: "Run regression tests", purpose: "Verify no breakage", canMutate: false, allowedTools: ["read","bash"], requiredInputs: ["patch"], expectedOutputs: ["test_results"], dependsOn: ["refactorer"] },
        { id: "auditor", agentProfile: "Audit the refactor", purpose: "Check boundaries", canMutate: false, allowedTools: ["read","search","lsp"], requiredInputs: ["patch","test_results"], expectedOutputs: ["audit_report"], dependsOn: ["refactorer","tester"] },
      ],
      gates: [{ id: "typecheck", kind: "typecheck", required: true, appliesAfter: ["refactorer"] }, { id: "tests", kind: "test", required: true, appliesAfter: ["tester"] }],
      budgets: { maxTimeMs: 1800000, maxParallelLanes: 2 },
      tools: { allow: ["read","write","edit","search","lsp","bash"], deny: [], requireApproval: [] },
      outputs: [{ kind: "patch", required: true }, { kind: "report", required: false }],
    },
  },
]
