-- DuckDB load script for normalized compute-research data
-- Generated by buildDuckDb
--
-- Normalized directory: /Users/user/Developer/GitHub/Tribunus/packages/compute-native/research-data/E0002-R1-20260609-canonical-norm
-- Timestamp: 2026-06-09T17:32:11.202Z

CREATE TABLE IF NOT EXISTS "runs" (
  "run_id" VARCHAR,
  "experiment_id" VARCHAR,
  "optimization_id" VARCHAR,
  "study_id" VARCHAR,
  "trial_index" INTEGER,
  "run_grade" VARCHAR,
  "status" VARCHAR,
  "start_time" VARCHAR,
  "end_time" VARCHAR,
  "source_revision" VARCHAR,
  "workload_id" VARCHAR,
  "machine_anon_id" VARCHAR,
  "machine_chip" VARCHAR,
  "machine_memory" VARCHAR,
  "model_image_hash" VARCHAR,
  "instrumentation_mode" VARCHAR,
  "page_cache_class" VARCHAR,
  "power_class" VARCHAR,
  "thermal_class" VARCHAR,
  "worker_id" VARCHAR,
  "event_count" BIGINT,
  "stage_event_count" BIGINT,
  "memory_sample_count" BIGINT,
  "token_metric_count" BIGINT,
  "checkpoint_count" BIGINT
);

CREATE TABLE IF NOT EXISTS "stage_events" (
  "run_id" VARCHAR,
  "request_id" VARCHAR,
  "worker_id" VARCHAR,
  "sequence_number" BIGINT,
  "event_type" VARCHAR,
  "clock_domain" VARCHAR,
  "monotonic_ns" BIGINT,
  "wall_ns" BIGINT,
  "stage_id" VARCHAR,
  "substrate_id" VARCHAR,
  "layer_index" INTEGER,
  "attention_kind" VARCHAR,
  "graph_region_id" VARCHAR,
  "kernel_id" VARCHAR,
  "stage_status" VARCHAR,
  "measurements" VARCHAR
);

CREATE TABLE IF NOT EXISTS "memory_samples" (
  "run_id" VARCHAR,
  "request_id" VARCHAR,
  "worker_id" VARCHAR,
  "sequence_number" BIGINT,
  "event_type" VARCHAR,
  "clock_domain" VARCHAR,
  "monotonic_ns" BIGINT,
  "wall_ns" BIGINT,
  "stage_id" VARCHAR,
  "substrate_id" VARCHAR,
  "layer_index" INTEGER,
  "resident_bytes" DOUBLE,
  "wired_bytes" DOUBLE,
  "active_bytes" DOUBLE,
  "compressed_bytes" DOUBLE
);

CREATE TABLE IF NOT EXISTS "token_metrics" (
  "run_id" VARCHAR,
  "request_id" VARCHAR,
  "worker_id" VARCHAR,
  "sequence_number" BIGINT,
  "event_type" VARCHAR,
  "clock_domain" VARCHAR,
  "monotonic_ns" BIGINT,
  "wall_ns" BIGINT,
  "token_index" BIGINT,
  "token_id" BIGINT,
  "decode_ns" DOUBLE,
  "attention_ns" DOUBLE,
  "mlp_ns" DOUBLE,
  "norm_ns" DOUBLE,
  "sample_ns" DOUBLE
);

CREATE TABLE IF NOT EXISTS "correctness_checkpoints" (
  "run_id" VARCHAR,
  "request_id" VARCHAR,
  "checkpoint_id" VARCHAR,
  "layer_or_stage" VARCHAR,
  "tensor_name" VARCHAR,
  "comparison_method" VARCHAR,
  "reference_hash" VARCHAR,
  "treatment_hash" VARCHAR,
  "max_abs_error" DOUBLE,
  "mean_abs_error" DOUBLE,
  "max_rel_error" DOUBLE,
  "mean_rel_error" DOUBLE,
  "cosine_similarity" DOUBLE,
  "tolerance" DOUBLE,
  "passed" BOOLEAN
);

-- Load data from NDJSON files

INSERT INTO "runs" SELECT * FROM read_json_auto('/Users/user/Developer/GitHub/Tribunus/packages/compute-native/research-data/E0002-R1-20260609-canonical-norm/.duckdb/ndjson/runs.ndjson');
INSERT INTO "stage_events" SELECT * FROM read_json_auto('/Users/user/Developer/GitHub/Tribunus/packages/compute-native/research-data/E0002-R1-20260609-canonical-norm/.duckdb/ndjson/stage_events.ndjson');
INSERT INTO "memory_samples" SELECT * FROM read_json_auto('/Users/user/Developer/GitHub/Tribunus/packages/compute-native/research-data/E0002-R1-20260609-canonical-norm/.duckdb/ndjson/memory_samples.ndjson');
