//! Graph family catalog — 7 normal + 1 baseline graph builders.
//!
//! Every graph uses only ops from the qualified 9-op envelope.
//! All weights use deterministic seeded random values.
//!
//! IMPORTANT: SSA names generated by MilBuilder use fresh_name(hint) which
//! appends "_counter". Counter starts at 0 for each new MilBuilder instance.
//! Every hardcoded name below is traced from counter=0.

use std::collections::HashMap;
use coreml_proto::proto::mil_spec::{self, argument, dimension, tensor_value, value};

use crate::mil_builder::MilBuilder;
use super::shape_profiles::ShapeProfile;

pub struct GraphFamily {
    pub name: &'static str,
    pub status: &'static str,
    pub op_count: u32,
    pub build: fn(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder,
}

// ── Seeded weights ────────────────────────────────────────────────────────

fn seeded_f32(seed: u64, len: usize) -> Vec<f32> {
    let mut state = seed;
    let mut out = vec![0.0f32; len];
    for v in out.iter_mut() {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        *v = ((state >> 32) as i32 as f32) * 1.0e-9_f32;
    }
    out
}

// ── Manual MIL ops (private helpers) ──────────────────────────────────────

fn manual_tensor_type(dtype: mil_spec::DataType, shape: &[u64]) -> mil_spec::TensorType {
    let dims: Vec<mil_spec::Dimension> = shape.iter().map(|&s| mil_spec::Dimension {
        dimension: Some(dimension::Dimension::Constant(dimension::ConstantDimension { size: s })),
    }).collect();
    mil_spec::TensorType { data_type: dtype as i32, rank: shape.len() as i64, dimensions: dims, attributes: HashMap::new() }
}

fn manual_value_type_tensor(tt: mil_spec::TensorType) -> mil_spec::ValueType {
    mil_spec::ValueType { r#type: Some(mil_spec::value_type::Type::TensorType(tt)) }
}

fn manual_named_arg(name: &str) -> mil_spec::Argument {
    mil_spec::Argument { arguments: vec![argument::Binding { binding: Some(argument::binding::Binding::Name(name.to_string())) }] }
}

fn manual_float32_value_type_2d(rows: u64, cols: u64) -> mil_spec::ValueType {
    manual_value_type_tensor(manual_tensor_type(mil_spec::DataType::Float32, &[rows, cols]))
}

fn manual_string_attr(val: &str) -> mil_spec::Value {
    let string_tensor = mil_spec::TensorValue {
        value: Some(tensor_value::Value::Strings(tensor_value::RepeatedStrings { values: vec![val.to_string()] })),
    };
    mil_spec::Value {
        doc_string: String::new(),
        r#type: Some(manual_value_type_tensor(mil_spec::TensorType {
            data_type: mil_spec::DataType::String as i32, rank: 0, dimensions: vec![], attributes: HashMap::new(),
        })),
        value: Some(value::Value::ImmediateValue(value::ImmediateValue {
            value: Some(value::immediate_value::Value::Tensor(string_tensor)),
        })),
    }
}

fn manual_int32s_attr(vals: &[i32]) -> mil_spec::Value {
    let int_tensor = mil_spec::TensorValue {
        value: Some(tensor_value::Value::Ints(tensor_value::RepeatedInts {
            values: vals.to_vec(),
        })),
    };
    mil_spec::Value {
        doc_string: String::new(),
        r#type: Some(manual_value_type_tensor(mil_spec::TensorType {
            data_type: mil_spec::DataType::Int64 as i32, rank: 1,
            dimensions: vec![mil_spec::Dimension {
                dimension: Some(dimension::Dimension::Constant(dimension::ConstantDimension { size: vals.len() as u64 })),
            }],
            attributes: HashMap::new(),
        })),
        value: Some(value::Value::ImmediateValue(value::ImmediateValue {
            value: Some(value::immediate_value::Value::Tensor(int_tensor)),
        })),
    }
}

fn op_silu(builder: MilBuilder, input: &str, out_name: &str) -> MilBuilder {
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    attrs.insert("mode".to_string(), manual_string_attr("silu"));
    let op = mil_spec::Operation {
        r#type: "element_wise".to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

fn op_sigmoid(builder: MilBuilder, input: &str, out_name: &str) -> MilBuilder {
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    attrs.insert("mode".to_string(), manual_string_attr("logistic"));
    let op = mil_spec::Operation {
        r#type: "element_wise".to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

fn op_softmax(builder: MilBuilder, input: &str, out_name: &str) -> MilBuilder {
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    let op = mil_spec::Operation {
        r#type: "softmax".to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

fn op_identity(builder: MilBuilder, input: &str, out_name: &str) -> MilBuilder {
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    let op = mil_spec::Operation {
        r#type: "identity".to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

fn op_transpose(builder: MilBuilder, input: &str, axes: &[i32], out_name: &str) -> MilBuilder {
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    attrs.insert("axes".to_string(), manual_int32s_attr(axes));
    let op = mil_spec::Operation {
        r#type: "transpose".to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

fn op_reshape(builder: MilBuilder, input: &str, target_shape: &[i32], out_name: &str) -> MilBuilder {
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    attrs.insert("shape".to_string(), manual_int32s_attr(target_shape));
    let op = mil_spec::Operation {
        r#type: "reshape".to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

// ── Graph builders (counter traced from 0) ────────────────────────────────

/// 1. matmul: counter traces: w_0, matmul_1
fn build_matmul(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(1, (profile.weight_rows * profile.weight_cols) as usize);
    builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()).const_f32("w", &w, &profile.weight_shape_i64())
        .matmul("x", "w_0")
        .output("matmul_1")
}

/// 2. chain_matmul_add_silu: w_0, matmul_1, bias_2, add_3, op_silu(→silu_4)
fn build_chain_matmul_add_silu(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(10, (profile.weight_rows * profile.weight_cols) as usize);
    let bias = seeded_f32(11, profile.weight_cols as usize);
    // SiLU(x) = x * sigmoid(x) — composite lowering is more portable than
    // native MIL silu op (coremlcompiler rejects element_wise mode "silu").
    let b = op_sigmoid(
        builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()).const_f32("w", &w, &profile.weight_shape_i64())
            .matmul("x", "w_0")
            .const_f32("bias", &bias, &[1, profile.weight_cols as i64])
            .add("matmul_1", "bias_2"),
        "add_3", "sig_3",
    );
    b.mul("add_3", "sig_3").output("mul_4")
}

/// 3. branch_rejoin: wa_0, wb_1, matmul_2, matmul_3, add_4
fn build_branch_rejoin(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let wa = seeded_f32(20, (profile.weight_rows * profile.weight_cols) as usize);
    let wb = seeded_f32(21, (profile.weight_rows * profile.weight_cols) as usize);
    builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()).const_f32("wa", &wa, &profile.weight_shape_i64())
        .const_f32("wb", &wb, &profile.weight_shape_i64())
        .matmul("x", "wa_0")
        .matmul("x", "wb_1")
        .add("matmul_2", "matmul_3")
        .output("add_4")
}

/// 4. multi_output: w_0, extra_1, matmul_2, add_3 → two outputs
fn build_multi_output(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(30, (profile.weight_rows * profile.weight_cols) as usize);
    let extra = seeded_f32(31, profile.input_cols as usize);
    builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()).const_f32("w", &w, &profile.weight_shape_i64())
        .const_f32("extra", &extra, &[1, profile.input_cols as i64])
        .matmul("x", "w_0")
        .add("x", "extra_1")
        .output("matmul_2")
        .output("add_3")
}

/// 5. constant_heavy: dummy_0_0..dummy_4_4, w_5, matmul_6
fn build_constant_heavy(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(40, (profile.weight_rows * profile.weight_cols) as usize);
    let mut b = builder;
    b = b.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64());
    for i in 0..5 {
        let dummy = seeded_f32(40 + i as u64, 16);
        // Hint "dummy_0" at counter 0 → "dummy_0_0"; counter 1 → "dummy_1_1"; etc.
        b = b.const_f32(&format!("dummy_{}", i), &dummy, &[4, 4]);
    }
    b.const_f32("w", &w, &profile.weight_shape_i64())
        .matmul("x", "w_5")
        .output("matmul_6")
}

/// 6. reshape_transpose_matmul: op_reshape(→"reshape_0"), op_transpose(→"transpose_1"),
///    op_reshape(→"reshape_2"), w_3, matmul_4
fn build_reshape_transpose_matmul(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(50, (profile.weight_rows * profile.weight_cols) as usize);
    let ic = profile.input_cols as i32;
    let b = builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64());
    let b = op_reshape(b, "x", &[1, ic, 1], "reshape_0");
    let b = op_transpose(b, "reshape_0", &[0, 2, 1], "transpose_1");
    let b = op_reshape(b, "transpose_1", &[1, ic], "reshape_2");
    b.const_f32("w", &w, &profile.weight_shape_i64())
        .matmul("reshape_2", "w_0")
        .output("matmul_1")
}

/// 7. softmax_tail: w_0, matmul_1, op_softmax(→"softmax_2")
fn build_softmax_tail(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(60, (profile.weight_rows * profile.weight_cols) as usize);
    let b = builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()).const_f32("w", &w, &profile.weight_shape_i64())
        .matmul("x", "w_0");
    let b = op_softmax(b, "matmul_1", "softmax_2");
    b.output("softmax_2")
}

fn build_identity_passthrough(builder: MilBuilder, _profile: &ShapeProfile) -> MilBuilder {
    // Identity: manual reshape with same shape. MIL has no "identity" op;
    // reshape with identical input/output shape is a valid MIL no-op.
    let b = builder.input("x", mil_spec::DataType::Float32, &_profile.input_shape_i64());
    let input_shape = _profile.input_shape_i64();
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg("x"));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr("identity_0"));
    let shape_attr = manual_int32s_attr(&input_shape.iter().map(|&s| s as i32).collect::<Vec<_>>());
    attrs.insert("shape".to_string(), shape_attr);
    let op = mil_spec::Operation {
        r#type: "reshape".to_string(),
        inputs,
        outputs: vec![mil_spec::NamedValueType { name: "identity_0".to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![],
        attributes: attrs,
    };
    b.operation(op, Some(("identity_0", vt))).output("identity_0")
}

// ── Catalog ───────────────────────────────────────────────────────────────

pub const NORMAL_FAMILIES: &[GraphFamily] = &[
    GraphFamily { name: "matmul", status: "normal", op_count: 1, build: build_matmul },
    GraphFamily { name: "chain_matmul_add_silu", status: "normal", op_count: 3, build: build_chain_matmul_add_silu },
    GraphFamily { name: "branch_rejoin", status: "normal", op_count: 3, build: build_branch_rejoin },
    GraphFamily { name: "multi_output", status: "normal", op_count: 2, build: build_multi_output },
    GraphFamily { name: "constant_heavy", status: "normal", op_count: 1, build: build_constant_heavy },
    GraphFamily { name: "reshape_transpose_matmul", status: "normal", op_count: 4, build: build_reshape_transpose_matmul },
    GraphFamily { name: "softmax_tail", status: "normal", op_count: 2, build: build_softmax_tail },
];

pub const BASELINE_FAMILIES: &[GraphFamily] = &[
    GraphFamily { name: "identity_passthrough", status: "baseline", op_count: 1, build: build_identity_passthrough },
];

pub fn all_families() -> Vec<&'static GraphFamily> {
    let mut v = Vec::with_capacity(NORMAL_FAMILIES.len() + BASELINE_FAMILIES.len());
    for f in NORMAL_FAMILIES { v.push(f); }
    for f in BASELINE_FAMILIES { v.push(f); }
    v
}

/// Canonical output SSA names per graph family.
///
/// SINGLE AUTHORITY for output names. Every caller (MIL package metadata,
/// Core ML predict, reference evaluator, harness) must use this mapping
/// instead of maintaining duplicates. The names are traced from counter=0
/// per MilBuilder instance, accounting for manual ops that don't advance
/// the counter.
pub fn graph_output_names(family_name: &str) -> &[&'static str] {
    match family_name {
        "matmul" => &["matmul_1"],
        "chain_matmul_add_silu" => &["mul_4"],
        "branch_rejoin" => &["add_4"],
        "multi_output" => &["matmul_2", "add_3"],
        "constant_heavy" => &["matmul_6"],
        "reshape_transpose_matmul" => &["matmul_1"],
        "softmax_tail" => &["softmax_2"],
        "identity_passthrough" => &["identity_0"],
        other => panic!("unknown family '{other}'"),
    }
}

/// Primary (first) output name for convenience.
pub fn graph_primary_output(family_name: &str) -> &'static str {
    graph_output_names(family_name)[0]
}
