//! Graph family catalog — 7 normal + 1 baseline graph builders.
//!
//! Every graph uses only ops from the qualified 9-op envelope.
//! All weights use deterministic seeded random values.
//!
//! IMPORTANT: SSA names generated by MilBuilder use fresh_name(hint) which
//! appends "_counter". Counter starts at 0 for each new MilBuilder instance.
//! Every hardcoded name below is traced from counter=0.

use std::collections::HashMap;
use coreml_proto::proto::mil_spec::{self, argument, dimension, tensor_value, value};

use crate::mil_builder::{MilBuilder, resolve_unary_op_type};
use super::shape_profiles::ShapeProfile;

pub struct GraphFamily {
    pub name: &'static str,
    pub status: &'static str,
    pub op_count: u32,
    pub build: fn(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder,
}

// ── Seeded weights ────────────────────────────────────────────────────────

fn seeded_f32(seed: u64, len: usize) -> Vec<f32> {
    let mut state = seed;
    let mut out = vec![0.0f32; len];
    for v in out.iter_mut() {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        *v = ((state >> 32) as i32 as f32) * 1.0e-9_f32;
    }
    out
}

// ── Manual MIL ops (private helpers) ──────────────────────────────────────

fn manual_tensor_type(dtype: mil_spec::DataType, shape: &[u64]) -> mil_spec::TensorType {
    let dims: Vec<mil_spec::Dimension> = shape.iter().map(|&s| mil_spec::Dimension {
        dimension: Some(dimension::Dimension::Constant(dimension::ConstantDimension { size: s })),
    }).collect();
    mil_spec::TensorType { data_type: dtype as i32, rank: shape.len() as i64, dimensions: dims, attributes: HashMap::new() }
}

fn manual_value_type_tensor(tt: mil_spec::TensorType) -> mil_spec::ValueType {
    mil_spec::ValueType { r#type: Some(mil_spec::value_type::Type::TensorType(tt)) }
}

fn manual_named_arg(name: &str) -> mil_spec::Argument {
    mil_spec::Argument { arguments: vec![argument::Binding { binding: Some(argument::binding::Binding::Name(name.to_string())) }] }
}

fn manual_float32_value_type_2d(rows: u64, cols: u64) -> mil_spec::ValueType {
    manual_value_type_tensor(manual_tensor_type(mil_spec::DataType::Float32, &[rows, cols]))
}

fn manual_string_attr(val: &str) -> mil_spec::Value {
    let string_tensor = mil_spec::TensorValue {
        value: Some(tensor_value::Value::Strings(tensor_value::RepeatedStrings { values: vec![val.to_string()] })),
    };
    mil_spec::Value {
        doc_string: String::new(),
        r#type: Some(manual_value_type_tensor(mil_spec::TensorType {
            data_type: mil_spec::DataType::String as i32, rank: 0, dimensions: vec![], attributes: HashMap::new(),
        })),
        value: Some(value::Value::ImmediateValue(value::ImmediateValue {
            value: Some(value::immediate_value::Value::Tensor(string_tensor)),
        })),
    }
}

fn manual_int32s_attr(vals: &[i32]) -> mil_spec::Value {
    let int_tensor = mil_spec::TensorValue {
        value: Some(tensor_value::Value::Ints(tensor_value::RepeatedInts {
            values: vals.to_vec(),
        })),
    };
    mil_spec::Value {
        doc_string: String::new(),
        r#type: Some(manual_value_type_tensor(mil_spec::TensorType {
            data_type: mil_spec::DataType::Int64 as i32, rank: 1,
            dimensions: vec![mil_spec::Dimension {
                dimension: Some(dimension::Dimension::Constant(dimension::ConstantDimension { size: vals.len() as u64 })),
            }],
            attributes: HashMap::new(),
        })),
        value: Some(value::Value::ImmediateValue(value::ImmediateValue {
            value: Some(value::immediate_value::Value::Tensor(int_tensor)),
        })),
    }
}

fn op_silu(builder: MilBuilder, input: &str, out_name: &str) -> MilBuilder {
    let entry = resolve_unary_op_type("silu")
        .expect("'silu' must have a mapped op type");
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    let op = mil_spec::Operation {
        r#type: entry.mil_op_type.to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

fn op_sigmoid(builder: MilBuilder, input: &str, out_name: &str) -> MilBuilder {
    let entry = resolve_unary_op_type("logistic")
        .expect("'logistic' must have a mapped op type");
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    // Use the input's shape for the output — sigmoid preserves dimensions.
    let input_dims = builder.value_shapes().get(input).cloned().unwrap_or(vec![1, 1]);
    let vt = manual_float32_value_type_2d(input_dims[0] as u64, input_dims[1] as u64);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    let op = mil_spec::Operation {
        r#type: entry.mil_op_type.to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

fn op_softmax(builder: MilBuilder, input: &str, out_name: &str) -> MilBuilder {
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    let op = mil_spec::Operation {
        r#type: "softmax".to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

fn op_identity(builder: MilBuilder, input: &str, out_name: &str) -> MilBuilder {
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    let op = mil_spec::Operation {
        r#type: "identity".to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

fn op_transpose(builder: MilBuilder, input: &str, axes: &[i32], out_name: &str) -> MilBuilder {
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    attrs.insert("axes".to_string(), manual_int32s_attr(axes));
    let op = mil_spec::Operation {
        r#type: "transpose".to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

fn op_reshape(builder: MilBuilder, input: &str, target_shape: &[i32], out_name: &str) -> MilBuilder {
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg(input));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr(out_name));
    attrs.insert("shape".to_string(), manual_int32s_attr(target_shape));
    let op = mil_spec::Operation {
        r#type: "reshape".to_string(),
        inputs, outputs: vec![mil_spec::NamedValueType { name: out_name.to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![], attributes: attrs,
    };
    builder.operation(op, Some((out_name, vt)))
}

// ── Graph builders (counter traced from 0) ────────────────────────────────

/// 1. matmul: counter traces: w_0, matmul_1
fn build_matmul(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(1, (profile.weight_rows * profile.weight_cols) as usize);
    builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()).const_f32("w", &w, &profile.weight_shape_i64())
        .matmul("x", "w_0")
        .output("matmul_1")
}

/// 2. chain_matmul_add_silu: w_0, matmul_1, bias_2, add_3, op_silu(→silu_4)
fn build_chain_matmul_add_silu(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(10, (profile.weight_rows * profile.weight_cols) as usize);
    let bias = seeded_f32(11, profile.weight_cols as usize);
    // SiLU(x) = x * sigmoid(x) — composite lowering is more portable than
    // native MIL silu op (coremlcompiler rejects element_wise mode "silu").
    let b = op_sigmoid(
        builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()).const_f32("w", &w, &profile.weight_shape_i64())
            .matmul("x", "w_0")
            .const_f32("bias", &bias, &[1, profile.weight_cols as i64])
            .add("matmul_1", "bias_2"),
        "add_3", "sig_3",
    );
    b.mul("add_3", "sig_3").output("mul_4")
}

/// 3. branch_rejoin: wa_0, wb_1, matmul_2, matmul_3, add_4
fn build_branch_rejoin(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let wa = seeded_f32(20, (profile.weight_rows * profile.weight_cols) as usize);
    let wb = seeded_f32(21, (profile.weight_rows * profile.weight_cols) as usize);
    builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()).const_f32("wa", &wa, &profile.weight_shape_i64())
        .const_f32("wb", &wb, &profile.weight_shape_i64())
        .matmul("x", "wa_0")
        .matmul("x", "wb_1")
        .add("matmul_2", "matmul_3")
        .output("add_4")
}

/// 4. multi_output: w_0, extra_1, matmul_2, add_3 → two outputs
fn build_multi_output(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(30, (profile.weight_rows * profile.weight_cols) as usize);
    let extra = seeded_f32(31, profile.input_cols as usize);
    builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()).const_f32("w", &w, &profile.weight_shape_i64())
        .const_f32("extra", &extra, &[1, profile.input_cols as i64])
        .matmul("x", "w_0")
        .add("x", "extra_1")
        .output("matmul_2")
        .output("add_3")
}

/// 5. constant_heavy: dummy_0_0..dummy_4_4, w_5, matmul_6
fn build_constant_heavy(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(40, (profile.weight_rows * profile.weight_cols) as usize);
    let mut b = builder;
    b = b.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64());
    for i in 0..5 {
        let dummy = seeded_f32(40 + i as u64, 16);
        // Hint "dummy_0" at counter 0 → "dummy_0_0"; counter 1 → "dummy_1_1"; etc.
        b = b.const_f32(&format!("dummy_{}", i), &dummy, &[4, 4]);
    }
    b.const_f32("w", &w, &profile.weight_shape_i64())
        .matmul("x", "w_5")
        .output("matmul_6")
}

/// 6. reshape_transpose_matmul: op_reshape(→"reshape_0"), op_transpose(→"transpose_1"),
///    op_reshape(→"reshape_2"), w_3, matmul_4
fn build_reshape_transpose_matmul(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(50, (profile.weight_rows * profile.weight_cols) as usize);
    let ic = profile.input_cols as i32;
    let b = builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64());
    let b = op_reshape(b, "x", &[1, ic, 1], "reshape_0");
    let b = op_transpose(b, "reshape_0", &[0, 2, 1], "transpose_1");
    let b = op_reshape(b, "transpose_1", &[1, ic], "reshape_2");
    b.const_f32("w", &w, &profile.weight_shape_i64())
        .matmul("reshape_2", "w_0")
        .output("matmul_1")
}

/// 7. softmax_tail: w_0, matmul_1, op_softmax(→"softmax_2")
fn build_softmax_tail(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(60, (profile.weight_rows * profile.weight_cols) as usize);
    let b = builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()).const_f32("w", &w, &profile.weight_shape_i64())
        .matmul("x", "w_0");
    let b = op_softmax(b, "matmul_1", "softmax_2");
    b.output("softmax_2")
}

fn build_identity_passthrough(builder: MilBuilder, _profile: &ShapeProfile) -> MilBuilder {
    // Identity: manual reshape with same shape. MIL has no "identity" op;
    // reshape with identical input/output shape is a valid MIL no-op.
    let b = builder.input("x", mil_spec::DataType::Float32, &_profile.input_shape_i64());
    let input_shape = _profile.input_shape_i64();
    let mut inputs = HashMap::new();
    inputs.insert("x".to_string(), manual_named_arg("x"));
    let vt = manual_float32_value_type_2d(1, 1);
    let mut attrs = HashMap::new();
    attrs.insert("name".to_string(), manual_string_attr("identity_0"));
    let shape_attr = manual_int32s_attr(&input_shape.iter().map(|&s| s as i32).collect::<Vec<_>>());
    attrs.insert("shape".to_string(), shape_attr);
    let op = mil_spec::Operation {
        r#type: "reshape".to_string(),
        inputs,
        outputs: vec![mil_spec::NamedValueType { name: "identity_0".to_string(), r#type: Some(vt.clone()) }],
        blocks: vec![],
        attributes: attrs,
    };
    b.operation(op, Some(("identity_0", vt))).output("identity_0")
}

// ── Tier 1 graph builders ─────────────────────────────────────────────────

fn build_add_standalone(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let n = profile.weight_cols as usize;
    let bias = seeded_f32(11, n);
    builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64())
        .const_f32("bias", &bias, &[1, profile.weight_cols as i64])
        .add("x", "bias_0")
        .output("add_1")
}

fn build_mul_standalone(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(12, (profile.weight_rows * profile.weight_cols) as usize);
    builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64())
        .const_f32("w", &w, &profile.weight_shape_i64())
        .mul("x", "w_0")
        .output("mul_1")
}

fn build_sigmoid_standalone(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    op_sigmoid(
        builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()),
        "x", "sig_0",
    )
    .output("sig_0")
}

fn build_silu_standalone(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    // SiLU(x) = x * sigmoid(x)
    let b = op_sigmoid(
        builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64()),
        "x", "sig_0",
    );
    b.mul("x", "sig_0").output("mul_0")
}

fn build_matmul_projection(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(1, (profile.weight_rows * profile.weight_cols) as usize);
    builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64())
        .const_f32("w", &w, &profile.weight_shape_i64())
        .matmul("x", "w_0")
        .output("matmul_1")
}

fn build_matmul_residual_add(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(1, (profile.weight_rows * profile.weight_cols) as usize);
    let bias = seeded_f32(11, profile.weight_cols as usize);
    builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64())
        .const_f32("w", &w, &profile.weight_shape_i64())
        .matmul("x", "w_0")
        .const_f32("bias", &bias, &[1, profile.weight_cols as i64])
        .add("matmul_1", "bias_2")
        .output("add_3")
}

fn build_two_matmul_add(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let wa = seeded_f32(20, (profile.weight_rows * profile.weight_cols) as usize);
    let wb = seeded_f32(21, (profile.weight_rows * profile.weight_cols) as usize);
    builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64())
        .const_f32("wa", &wa, &profile.weight_shape_i64())
        .const_f32("wb", &wb, &profile.weight_shape_i64())
        .matmul("x", "wa_0")
        .matmul("x", "wb_1")
        .add("matmul_2", "matmul_3")
        .output("add_4")
}

fn build_matmul_add_silu(builder: MilBuilder, profile: &ShapeProfile) -> MilBuilder {
    let w = seeded_f32(10, (profile.weight_rows * profile.weight_cols) as usize);
    let bias = seeded_f32(11, profile.weight_cols as usize);
    let b = op_sigmoid(
        builder.input("x", mil_spec::DataType::Float32, &profile.input_shape_i64())
            .const_f32("w", &w, &profile.weight_shape_i64())
            .matmul("x", "w_0")
            .const_f32("bias", &bias, &[1, profile.weight_cols as i64])
            .add("matmul_1", "bias_2"),
        "add_3", "sig_3",
    );
    b.mul("add_3", "sig_3").output("mul_4")
}

// ── Catalog ───────────────────────────────────────────────────────────────

pub const NORMAL_FAMILIES: &[GraphFamily] = &[
    GraphFamily { name: "matmul", status: "normal", op_count: 1, build: build_matmul },
    GraphFamily { name: "chain_matmul_add_silu", status: "normal", op_count: 3, build: build_chain_matmul_add_silu },
    GraphFamily { name: "branch_rejoin", status: "normal", op_count: 3, build: build_branch_rejoin },
    GraphFamily { name: "multi_output", status: "normal", op_count: 2, build: build_multi_output },
    GraphFamily { name: "constant_heavy", status: "normal", op_count: 1, build: build_constant_heavy },
    GraphFamily { name: "reshape_transpose_matmul", status: "normal", op_count: 4, build: build_reshape_transpose_matmul },
    GraphFamily { name: "softmax_tail", status: "normal", op_count: 2, build: build_softmax_tail },
];

pub const BASELINE_FAMILIES: &[GraphFamily] = &[
    GraphFamily { name: "identity_passthrough", status: "baseline", op_count: 1, build: build_identity_passthrough },
];

pub const TIER1_FAMILIES: &[GraphFamily] = &[
    GraphFamily { name: "add_standalone", status: "tier1", op_count: 1, build: build_add_standalone },
    GraphFamily { name: "mul_standalone", status: "tier1", op_count: 1, build: build_mul_standalone },
    GraphFamily { name: "sigmoid_standalone", status: "tier1", op_count: 1, build: build_sigmoid_standalone },
    GraphFamily { name: "silu_standalone", status: "tier1", op_count: 2, build: build_silu_standalone },
    GraphFamily { name: "matmul_projection", status: "tier1", op_count: 1, build: build_matmul_projection },
    GraphFamily { name: "matmul_residual_add", status: "tier1", op_count: 2, build: build_matmul_residual_add },
    GraphFamily { name: "two_matmul_add", status: "tier1", op_count: 3, build: build_two_matmul_add },
    GraphFamily { name: "matmul_add_silu", status: "tier1", op_count: 3, build: build_matmul_add_silu },
];

/// Tier 2 decode Batch 1 family names (no build function — uses DecodeShapeBinding).
/// Build functions are implemented in harness.rs / backend_adapters.
pub const DECODE_BATCH1_NAMES: &[&str] = &[
    "decode_qkv_projection",
    "decode_attention_output_projection",
    "decode_residual_add_1",
    "decode_mlp_gate_up_silu",
    "decode_mlp_down",
    "decode_residual_add_2",
    "decode_lm_head",
];

/// Tier 2 Batch 1 family op counts (used for summary metadata when no GraphFamily build available).
pub const DECODE_BATCH1_OP_COUNTS: &[u32] = &[
    1, // decode_qkv_projection: matmul [hidden_dim, 3*hidden_dim]
    1, // decode_attention_output_projection: matmul [hidden_dim, hidden_dim]
    1, // decode_residual_add_1: element-wise add
    4, // decode_mlp_gate_up_silu: matmul(gate) + matmul(up) + sigmoid + mul
    1, // decode_mlp_down: matmul [intermediate_dim, hidden_dim]
    1, // decode_residual_add_2: element-wise add
    1, // decode_lm_head: matmul [hidden_dim, vocab_dim]
];

/// Combine all family lists.
pub fn all_families() -> Vec<&'static GraphFamily> {
    let mut v = Vec::with_capacity(NORMAL_FAMILIES.len() + BASELINE_FAMILIES.len());
    for f in NORMAL_FAMILIES { v.push(f); }
    for f in BASELINE_FAMILIES { v.push(f); }
    v
}

/// Canonical output SSA names per graph family.
///
/// SINGLE AUTHORITY for output names. Every caller (MIL package metadata,
/// Core ML predict, reference evaluator, harness) must use this mapping
/// instead of maintaining duplicates. The names are traced from counter=0
/// per MilBuilder instance, accounting for manual ops that don't advance
/// the counter.
pub fn graph_output_names(family_name: &str) -> &[&'static str] {
    match family_name {
        "matmul" => &["matmul_1"],
        "chain_matmul_add_silu" => &["mul_4"],
        "branch_rejoin" => &["add_4"],
        "multi_output" => &["matmul_2", "add_3"],
        "constant_heavy" => &["matmul_6"],
        "reshape_transpose_matmul" => &["matmul_1"],
        "softmax_tail" => &["softmax_2"],
        "identity_passthrough" => &["identity_0"],
        "add_standalone" => &["add_1"],
        "mul_standalone" => &["mul_1"],
        "sigmoid_standalone" => &["sig_0"],
        "silu_standalone" => &["mul_0"],
        "matmul_projection" => &["matmul_1"],
        "matmul_residual_add" => &["add_3"],
        "two_matmul_add" => &["add_4"],
        "matmul_add_silu" => &["mul_4"],
        "decode_qkv_projection" => &["matmul_qkv"],
        "decode_attention_output_projection" => &["matmul_attn_out"],
        "decode_residual_add_1" => &["add_residual_1"],
        "decode_mlp_gate_up_silu" => &["mul_gated"],
        "decode_mlp_down" => &["matmul_mlp_down"],
        "decode_residual_add_2" => &["add_residual_2"],
        "decode_lm_head" => &["matmul_lm_head"],
        other => panic!("unknown family '{other}'"),
    }
}

/// Primary (first) output name for convenience.
pub fn graph_primary_output(family_name: &str) -> &'static str {
    graph_output_names(family_name)[0]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mil_builder::MilBuilder;
    use crate::decode_attribution::suite_manifest::{tier0_manifest, tier1_manifest};
    use crate::decode_attribution::shape_profiles::{SMALL, MEDIUM};

    /// Every manifest family must have its graph_output_names() entries
    /// produced by the actual graph builder for both small and medium shapes.
    #[test]
    fn graph_output_names_are_produced_for_all_manifest_families() {
        // Collect unique family names from the manifest (the suite authority)
        let t0 = tier0_manifest();
        let t1 = tier1_manifest();
        let mut families: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
        for row in t0.rows.iter().chain(t1.rows.iter()) {
            families.insert(row.family.as_str());
        }

        // Build a lookup from family name to GraphFamily
        let catalog: std::collections::HashMap<&str, &GraphFamily> =
            NORMAL_FAMILIES.iter()
                .chain(BASELINE_FAMILIES.iter())
                .chain(TIER1_FAMILIES.iter())
                .map(|f| (f.name, f))
                .collect();

        for family_name in &families {
            let family = catalog.get(family_name)
                .unwrap_or_else(|| panic!("family '{family_name}' in manifest but not in catalog"));

            for profile in &[SMALL, MEDIUM] {
                let builder = MilBuilder::new("test");
                let builder = (family.build)(builder, profile);
                let program = builder.build()
                    .unwrap_or_else(|e| panic!("build failed for {} shape {}: {}", family.name, profile.name, e));

                // Collect all SSA names produced by the program
                let mut produced_names: std::collections::HashSet<&str> = std::collections::HashSet::new();
                for func in program.functions.values() {
                    for block in func.block_specializations.values() {
                        for op in &block.operations {
                            for out in &op.outputs {
                                produced_names.insert(out.name.as_str());
                            }
                        }
                    }
                }

                let expected = graph_output_names(family.name);
                for name in expected {
                    assert!(
                        produced_names.contains(name),
                        "family '{}' shape '{}': expected output name '{}' not found in produced SSA names {:?}",
                        family.name, profile.name, name, produced_names
                    );
                }
            }
        }
    }
}
