use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecodeAttributionReceipt {
    pub run_id: String,
    pub commit_sha: String,
    pub branch: String,
    pub timestamp: String,
    pub schema_version: String,
    pub host_chip: String,
    pub macos_version: String,
    pub xcode_version: String,
    pub coremlcompiler_version: String,
    pub graph_family: String,
    pub shape_profile: String,
    pub graph_status: String,
    pub op_count: u32,
    pub input_shape: Vec<u32>,
    pub weight_shape: Vec<u32>,
    pub output_shapes: Vec<Vec<u32>>,
    pub dtype: String,
    pub matrix_name: String,
    pub matrix_required: bool,
    pub configured_warmup_iterations: u32,
    pub configured_steady_iterations: u32,
    pub tolerance: f64,
    pub percentile_method: String,
    pub materialize_duration_ns: u64,
    pub source_package_sha256: String,
    pub compile_duration_ns: u64,
    pub compiled_artifact_sha256: String,
    pub compile_exit_status: i32,
    pub compile_diagnostics: Vec<String>,
    pub compiler_stdout_sha256: String,
    pub compiler_stderr_sha256: String,
    pub compiler_stdout_sidecar_path: Option<String>,
    pub compiler_stderr_sidecar_path: Option<String>,
    pub runtime_compute_units: String,
    pub backend: String,
    pub backend_runtime_policy: String,
    pub backend_support_status: String,
    pub backend_prepare_duration_ns: u64,
    pub materialization_kind: String,
    pub compile_kind: String,
    pub load_kind: String,
    pub execution_kind: String,
    pub materialize_status: String,
    pub compile_status: String,
    pub load_status: String,
    pub cold_status: String,
    pub warmup_status: String,
    pub steady_status: String,
    pub reference_status: String,
    pub mlx_device: String,
    pub mlx_eval_forced: bool,
    pub mlx_eval_method: String,
    pub load_duration_ns: u64,
    pub load_success: bool,
    pub model_description_summary: Option<String>,
    pub compute_plan_status: String,
    pub compute_plan_summary: Option<String>,
    pub cold_first_predict_ns: u64,
    pub cold_output_hashes: Vec<String>,
    pub warmup_iterations: u32,
    pub warmup_total_ns: u64,
    pub steady_iterations: u32,
    pub steady_sample_ns: Vec<u64>,
    pub steady_total_ns: u64,
    pub steady_p50_ns: u64,
    pub steady_p90_ns: u64,
    pub steady_p99_ns: u64,
    pub steady_min_ns: u64,
    pub steady_max_ns: u64,
    pub steady_mean_ns: f64,
    pub steady_stddev_ns: f64,
    pub steady_mad_ns: f64,
    pub steady_iqr_ns: f64,
    pub steady_outlier_count: u32,
    pub memory_measurement_method: String,
    pub process_rss_before_materialize_kb: u64,
    pub process_rss_before_load_kb: u64,
    pub process_rss_after_load_kb: u64,
    pub process_rss_after_cold_predict_kb: u64,
    pub process_rss_after_steady_kb: u64,
    pub max_absolute_error: f64,
    pub max_relative_error: f64,
    pub mean_absolute_error: f64,
    pub cosine_similarity: f64,
    pub matches_tolerance: bool,
    pub reference_output_hashes: Vec<String>,
    /// True when reference evaluator ran and produced hashes for this row (always true in lattice mode).
    pub reference_output_hashes_populated: bool,
    pub accelerate_status: String,
    pub accelerate_duration_ns: Option<u64>,
    pub accelerate_output_hashes: Vec<String>,
    pub status: String,
    /// Observed runtime outcome: pass | materialize_limited | compile_limited | load_blocked | predict_blocked | numerical_divergence | timeout | memory_oom | skipped_by_support.
    pub predict_status: String,
    /// Phase-specific failure classification for non-pass rows.
    pub predict_failure_classification: String,
    /// Static capability tier: supported_native | supported_composed | unsupported_graph | not_implemented.
    pub support_tier: String,
    /// True if package SHA changed between runs for same graph/shape (determinism failure).
    pub package_determinism_failure: bool,
    pub failure_reason: Option<String>,
    /// True if MLX compile() was attempted (false for this gate; future gates may set true).
    pub mlx_compile_attempted: bool,
    /// MLX phase-split timing: time to construct MLX arrays from host data.
    pub mlx_array_construct_ns: u64,
    /// MLX phase-split timing: time to build lazy graph nodes (ops, no eval).
    pub mlx_graph_build_ns: u64,
    /// MLX phase-split timing: time for .eval() only (no graph build, no readback).
    pub mlx_eval_only_ns: u64,
    /// MLX phase-split timing: time to read output back to host (.try_as_slice).
    pub mlx_readback_ns: u64,
    /// True if MLX cache hit (plan cache reuse) — always false for this gate.
    pub mlx_cache_hit: bool,
    /// Time spent in Python boundary (ns) — 0 for Rust-native, nonzero placeholder for future Python path.
    pub python_boundary_ns: Option<u64>,
}

impl Default for DecodeAttributionReceipt {
    fn default() -> Self {
        Self {
            run_id: String::new(),
            commit_sha: String::new(),
            branch: String::new(),
            timestamp: String::new(),
            schema_version: String::new(),
            host_chip: String::new(),
            macos_version: String::new(),
            xcode_version: String::new(),
            coremlcompiler_version: String::new(),
            graph_family: String::new(),
            shape_profile: String::new(),
            graph_status: String::new(),
            op_count: 0,
            input_shape: vec![],
            weight_shape: vec![],
            output_shapes: vec![],
            dtype: String::new(),
            matrix_name: String::new(),
            matrix_required: false,
            configured_warmup_iterations: 0,
            configured_steady_iterations: 0,
            tolerance: 0.0,
            percentile_method: String::new(),
            materialize_duration_ns: 0,
            source_package_sha256: String::new(),
            compile_duration_ns: 0,
            compiled_artifact_sha256: String::new(),
            compile_exit_status: 0,
            compile_diagnostics: vec![],
            compiler_stdout_sha256: String::new(),
            compiler_stderr_sha256: String::new(),
            compiler_stdout_sidecar_path: None,
            compiler_stderr_sidecar_path: None,
            runtime_compute_units: String::new(),
            backend: String::new(),
            backend_runtime_policy: String::new(),
            backend_support_status: String::new(),
            backend_prepare_duration_ns: 0,
            materialization_kind: String::new(),
            compile_kind: String::new(),
            load_kind: String::new(),
            execution_kind: String::new(),
            materialize_status: String::new(),
            compile_status: String::new(),
            load_status: String::new(),
            cold_status: String::new(),
            warmup_status: String::new(),
            steady_status: String::new(),
            reference_status: String::new(),
            mlx_device: String::new(),
            mlx_eval_forced: false,
            mlx_eval_method: String::new(),
            load_duration_ns: 0,
            load_success: false,
            model_description_summary: None,
            compute_plan_status: String::new(),
            compute_plan_summary: None,
            cold_first_predict_ns: 0,
            cold_output_hashes: vec![],
            warmup_iterations: 0,
            warmup_total_ns: 0,
            steady_iterations: 0,
            steady_sample_ns: vec![],
            steady_total_ns: 0,
            steady_p50_ns: 0,
            steady_p90_ns: 0,
            steady_p99_ns: 0,
            steady_min_ns: 0,
            steady_max_ns: 0,
            steady_mean_ns: 0.0,
            steady_stddev_ns: 0.0,
            steady_mad_ns: 0.0,
            steady_iqr_ns: 0.0,
            steady_outlier_count: 0,
            memory_measurement_method: String::new(),
            process_rss_before_materialize_kb: 0,
            process_rss_before_load_kb: 0,
            process_rss_after_load_kb: 0,
            process_rss_after_cold_predict_kb: 0,
            process_rss_after_steady_kb: 0,
            max_absolute_error: 0.0,
            max_relative_error: 0.0,
            mean_absolute_error: 0.0,
            cosine_similarity: 0.0,
            matches_tolerance: false,
            reference_output_hashes: vec![],
            reference_output_hashes_populated: false,
            accelerate_status: String::new(),
            accelerate_duration_ns: None,
            accelerate_output_hashes: vec![],
            status: String::new(),
            predict_status: String::new(),
            predict_failure_classification: String::new(),
            support_tier: String::new(),
            package_determinism_failure: false,
            failure_reason: None,
            mlx_compile_attempted: false,
            mlx_array_construct_ns: 0,
            mlx_graph_build_ns: 0,
            mlx_eval_only_ns: 0,
            mlx_readback_ns: 0,
            mlx_cache_hit: false,
            python_boundary_ns: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json;

    #[test]
    fn json_round_trip() {
        let receipt = DecodeAttributionReceipt::default();
        let json = serde_json::to_string(&receipt).expect("serialize");
        let deserialized: DecodeAttributionReceipt =
            serde_json::from_str(&json).expect("deserialize");
        assert_eq!(receipt.run_id, deserialized.run_id);
    }

    #[test]
    fn json_round_trip_with_custom_run_id() {
        let receipt = DecodeAttributionReceipt {
            run_id: "DA-0001-20260610".to_string(),
            ..DecodeAttributionReceipt::default()
        };
        let json = serde_json::to_string(&receipt).expect("serialize");
        let deserialized: DecodeAttributionReceipt =
            serde_json::from_str(&json).expect("deserialize");
        assert_eq!(deserialized.run_id, "DA-0001-20260610");
    }
}
